name: audio_waveforms
description: A Flutter package that allow you to generate waveform while recording audio or from audio file.
version: 2.0.0
homepage: https://github.com/SimformSolutionsPvtLtd/audio_waveforms
issue_tracker: https://github.com/SimformSolutionsPvtLtd/audio_waveforms/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.10.4
  just_waveform: ^0.0.7
  record: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.5.4


flutter:
  plugin:
    platforms:
      android:
        package: com.simform.audio_waveforms
        pluginClass: AudioWaveformsPlugin
      ios:
        pluginClass: AudioWaveformsPlugin
      macos:
        pluginClass: AudioWaveformsPlugin
      windows:
        pluginClass: AudioWaveformsPlugin
      linux:
        pluginClass: AudioWaveformsPlugin

platforms:
  android:
  ios:
  macos:
  windows:
  linux:

